### PR TITLE
use different warehouse in checker

### PR DESCRIPTION
**Pull request by ondrajodas**
Cannot access object or it does not exist. Executing query "USE WAREHOUSE "WH_KEBOOLA""

narazili jsme na to ještě u Checku dat

po téhle úpravě to je otestované tu - https://connection.eu-central-1.keboola.com/admin/projects/3829/queue/797200386

a funguje

### CODE REVIEW

**Comment by romantmb** [comment]
[Tu](https://connection.eu-central-1.keboola.com/admin/projects/3829/queue/797200386) to vyfailovalo. 🙂

**Comment by ondrajodas** [comment]
no to je marcovou změnou :D
https://github.com/keboola/project-migration-tool/pull/37

**Comment by ondrajodas** [comment]
něco s tím vymyslím no

**Comment by ondrajodas** [comment]
@romantmb ten marcuv PR sem revertnul a už je to zelený - https://connection.eu-central-1.keboola.com/admin/projects/3829/queue/797211741 :D

**Review by romantmb — APPROVED** [review]
👍

**Pull request merged**
